version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      TFM_DB_USER: root
      TFM_DB_HOST: db
    volumes:
      - .:/app
    depends_on:
      - db
    command: bin/rails s -p 3000 -b '0.0.0.0'
  db:
    image: postgres:9.6.11
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
