default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['TFM_DB_USER'] %>
  password: <%= ENV['TFM_DB_PASSWORD'] %>
  host: <%= ENV['TFM_DB_HOST'] %>
  port: <%= ENV['TFM_DB_PORT'] %>


development:
  <<: *default
  database: twitter_fav_manager_development

test:
  <<: *default
  database: twitter_fav_manager_test

production:
  <<: *default
  database: twitter_fav_manager_production
